from __future__ import annotations

from typing import Protocol

from app.clinical.canonical import CanonicalAggregateResult, CanonicalClinicalQuery


class ClinicalAnalyticsAdapter(Protocol):
    """Database-neutral port for aggregate-only clinical analytics."""

    def inspect_trial(self, trial_id: str, source_batch_id: str | None = None) -> CanonicalAggregateResult: ...
    def compare_treatment_effect(self, query: CanonicalClinicalQuery) -> CanonicalAggregateResult: ...
    def check_randomization_balance(self, query: CanonicalClinicalQuery) -> CanonicalAggregateResult: ...
    def analyze_missingness(self, query: CanonicalClinicalQuery, group_by: str = "treatment_arm") -> CanonicalAggregateResult: ...
    def profile_sites(self, query: CanonicalClinicalQuery) -> CanonicalAggregateResult: ...
    def inspect_treatment_exposure(self, trial_id: str, site_id: str | None, source_batch_id: str | None = None, source_domains: frozenset[str] = frozenset(), group_by: str = "site") -> CanonicalAggregateResult: ...
    def inspect_protocol_quality(self, trial_id: str, site_id: str | None, source_batch_id: str | None = None, source_domains: frozenset[str] = frozenset(), group_by: str = "site", measure: str | None = None) -> CanonicalAggregateResult: ...
    def empty_for_unavailable_batch(self, operation: str, source_batch_id: str) -> CanonicalAggregateResult: ...
    def empty_for_unbound_mart(self, operation: str, source_batch_id: str) -> CanonicalAggregateResult: ...
    def inspect_safety_summary(self, query: CanonicalClinicalQuery) -> CanonicalAggregateResult: ...
    def analyze_safety_trend(self, query: CanonicalClinicalQuery) -> CanonicalAggregateResult: ...
    def analyze_visit_windows(self, query: CanonicalClinicalQuery) -> CanonicalAggregateResult: ...
    def inspect_data_quality(self, query: CanonicalClinicalQuery) -> CanonicalAggregateResult: ...
    def rank_sites(
        self,
        query: CanonicalClinicalQuery,
        group_by: str = "site",
        source_batch_id: str | None = None,
        source_domains: frozenset[str] = frozenset(),
    ) -> CanonicalAggregateResult: ...
    def build_subgroup_forest(self, query: CanonicalClinicalQuery, group_by: str = "region") -> CanonicalAggregateResult: ...
    def run_sensitivity_analysis(
        self,
        query: CanonicalClinicalQuery,
        analysis_method: str = "leave_one_site_out",
    ) -> CanonicalAggregateResult: ...

