import type {CdiscBatch,CdiscPreview,CdiscPublishAssessment,CdiscPublishedBatch,ClinicalCatalogSnapshot,ClinicalDataSpace,ClinicalTrialCatalogItem,DynamicState,Investigation,InvestigationSpace,QuarantineBatch,QuarantineSchema,Role,SmartImportInspection,UnderstandingResult,ValidationResult} from './types';
const headers={'X-InsightFlow-User':'clinical-analyst-asia'};
const userHeader=(role:Role)=>({'X-InsightFlow-User':role==='admin'?'admin':'clinical-analyst-asia'});
export async function listInvestigations(role:Role='analyst'):Promise<Investigation[]>{const response=await fetch('/api/v4/clinical/investigations',{headers:userHeader(role)});if(!response.ok)throw new Error('无法加载临床调查');return response.json()}
export async function listPublishedCdiscBatches(role:Role='analyst'):Promise<CdiscPublishedBatch[]>{const response=await fetch('/api/v5/clinical/imports/published-batches',{headers:{'X-InsightFlow-User':role==='admin'?'admin':'clinical-analyst-asia'}});if(!response.ok)throw new Error('无法加载已发布数据版本');return response.json()}
export async function listClinicalTrials(role:Role='analyst'):Promise<ClinicalTrialCatalogItem[]>{const response=await fetch('/api/v8/clinical/trials',{headers:userHeader(role)});if(!response.ok)throw new Error('无法加载当前身份可访问的临床试验');return response.json()}
export async function getClinicalCatalog(trialId:string,role:Role='analyst'):Promise<ClinicalCatalogSnapshot>{const response=await fetch(`/api/v15/clinical/catalog?trial_id=${encodeURIComponent(trialId)}`,{headers:userHeader(role)});if(!response.ok)throw new Error('无法加载真实数据目录');return response.json()}
export async function createClinicalInvestigation(payload:{trial_id:string;question:string;subgroup?:string;batch_id?:string},role:Role='analyst'):Promise<Investigation>{const response=await fetch('/api/v4/clinical/investigations',{method:'POST',headers:{...userHeader(role),'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!response.ok){const error=await response.json().catch(()=>null);throw new Error(error?.detail?.message??'临床调查创建失败')}return response.json()}
export async function previewCdiscImport(files:{dm:File;adsl:File;adeff:File},mapping:string,role:Role):Promise<CdiscPreview>{const body=new FormData();body.append('dm',files.dm);body.append('adsl',files.adsl);body.append('adeff',files.adeff);body.append('mapping_json',mapping);const response=await fetch('/api/v5/clinical/imports/preview',{method:'POST',headers:{'X-InsightFlow-User':role==='admin'?'admin':'clinical-analyst-asia'},body});if(!response.ok){const error=await response.json().catch(()=>null);throw new Error(error?.detail?.message??'CDISC 质量预检失败')}return response.json()}
export async function commitCdiscImport(token:string):Promise<CdiscBatch>{const response=await fetch('/api/v5/clinical/imports/commit',{method:'POST',headers:{'X-InsightFlow-User':'admin','Content-Type':'application/json'},body:JSON.stringify({token})});if(!response.ok){const error=await response.json().catch(()=>null);throw new Error(error?.detail?.message??'确认导入失败')}return response.json()}
export async function assessCdiscPublish(batchId:string):Promise<CdiscPublishAssessment>{const response=await fetch(`/api/v5/clinical/imports/${batchId}/publish-assessment`,{headers:{'X-InsightFlow-User':'admin'}});if(!response.ok)throw new Error('无法评估分析发布条件');return response.json()}
export async function publishCdiscBatch(batchId:string):Promise<CdiscBatch>{const response=await fetch(`/api/v5/clinical/imports/${batchId}/publish`,{method:'POST',headers:{'X-InsightFlow-User':'admin'}});if(!response.ok){const error=await response.json().catch(()=>null);throw new Error(error?.detail?.message??'发布到分析层失败')}return response.json()}
export async function inspectClinicalFiles(files:File[],role:Role,provider='auto'):Promise<SmartImportInspection>{const body=new FormData();files.forEach(file=>body.append('files',file));body.append('provider',provider);const response=await fetch('/api/v7/clinical/imports/inspect',{method:'POST',headers:userHeader(role),body});if(!response.ok){const error=await response.json().catch(()=>null);throw new Error(error?.detail?.message??'智能文件识别失败')}return response.json()}
export async function previewSmartClinicalFiles(files:File[],mapping:string,role:Role):Promise<CdiscPreview>{const body=new FormData();files.forEach(file=>body.append('files',file));body.append('mapping_json',mapping);const response=await fetch('/api/v7/clinical/imports/preview',{method:'POST',headers:userHeader(role),body});if(!response.ok){const error=await response.json().catch(()=>null);throw new Error(error?.detail?.message??'智能映射质量预检失败')}return response.json()}
export async function runDynamicInvestigation(payload:{question:string;trial_id:string;provider:string;model?:string;published_batch_id?:string},role:Role):Promise<DynamicState>{const response=await fetch('/api/v8/clinical/investigations',{method:'POST',headers:{...userHeader(role),'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!response.ok){const e=await response.json().catch(()=>null);const messages:Record<string,string>={resource_not_found:'试验不存在、当前身份无权访问，或所选数据版本与试验不匹配',permission_denied:'当前身份无权发起临床调查',authentication_required:'登录身份无效，请重新选择身份'};throw new Error(e?.detail?.message??messages[e?.detail?.code]??'动态调查启动失败')}return response.json()}
export async function listClinicalDataSpaces(role:Role):Promise<ClinicalDataSpace[]>{const response=await fetch('/api/v10/clinical/data-spaces',{headers:userHeader(role)});if(!response.ok)throw new Error('无法加载临床数据目录');return response.json()}
export async function runPublicClinicalInvestigation(payload:{question:string;subject:string;space:Exclude<InvestigationSpace,'clinical_trial'>;provider:string;model?:string},role:Role):Promise<DynamicState>{const response=await fetch('/api/v10/clinical/public-investigations',{method:'POST',headers:{...userHeader(role),'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!response.ok){const e=await response.json().catch(()=>null);throw new Error(e?.detail?.message??'公共临床数据调查启动失败')}return response.json()}
export async function uploadQuarantine(files:File[],role:Role):Promise<QuarantineBatch>{const body=new FormData();files.forEach(file=>body.append('files',file));const response=await fetch('/api/v8/imports',{method:'POST',headers:userHeader(role),body});if(!response.ok){const e=await response.json().catch(()=>null);throw new Error(e?.detail?.message??'文件无法进入隔离区')}return response.json()}
export async function profileQuarantine(batch:QuarantineBatch,role:Role):Promise<QuarantineSchema>{const response=await fetch(`/api/v8/imports/${batch.batch_id}/profile`,{method:'POST',headers:{...userHeader(role),'Content-Type':'application/json'},body:JSON.stringify({version:batch.version})});if(!response.ok){const e=await response.json().catch(()=>null);throw new Error(e?.detail?.message??'数据画像生成失败')}return response.json()}
export async function understandQuarantine(batch:QuarantineBatch,role:Role):Promise<UnderstandingResult>{const response=await fetch(`/api/v8/imports/${batch.batch_id}/understand`,{method:'POST',headers:{...userHeader(role),'Content-Type':'application/json'},body:JSON.stringify({version:batch.version,provider:'rules'})});if(!response.ok){const e=await response.json().catch(()=>null);throw new Error(e?.detail?.message??'数据域理解失败')}return response.json()}
export async function validateQuarantine(batch:QuarantineBatch,role:Role):Promise<ValidationResult>{const response=await fetch(`/api/v8/imports/${batch.batch_id}/validate`,{method:'POST',headers:{...userHeader(role),'Content-Type':'application/json'},body:JSON.stringify({version:batch.version})});if(!response.ok){const e=await response.json().catch(()=>null);throw new Error(e?.detail?.message??'映射验证失败')}return response.json()}
export async function advanceQuarantine(batch:QuarantineBatch,action:'approve'|'publish'):Promise<QuarantineBatch>{const response=await fetch(`/api/v8/imports/${batch.batch_id}/${action}`,{method:'POST',headers:{'X-InsightFlow-User':'admin','Content-Type':'application/json'},body:JSON.stringify({version:batch.version})});if(!response.ok){const e=await response.json().catch(()=>null);throw new Error(e?.detail?.message??'生命周期操作失败')}return response.json()}

