import {useEffect,useState} from 'react';
import {Button,Content,Header,HeaderName,Tag,Tabs,TabList,Tab,TabPanels,TabPanel} from '@carbon/react';
import {DataBase,Document,Time,Upload,Activity} from '@carbon/icons-react';
import type {CdiscPublishedBatch,Investigation,Role} from './types';
import {createClinicalInvestigation,listInvestigations,listPublishedCdiscBatches} from './api';
import {ClinicalSafetyPanel} from './clinical/ClinicalSafetyPanel';
import {CdiscImportWorkspace} from './clinical/CdiscImportWorkspace';
import {DataUnderstandingWorkspace} from './clinical/DataUnderstandingWorkspace';
import {InvestigationComposer} from './clinical/InvestigationComposer';
import {DataCatalogPanel} from './clinical/DataCatalogPanel';
import './styles.css';

const labels:Record<string,string>={published:'已发布',pending_approval:'待审批',draft:'草稿',rejected:'已驳回'};
export function App({initialRole='analyst',initialInvestigation}: {initialRole?:Role;initialInvestigation?:Investigation|null}){
 const [role,setRole]=useState<Role>(initialRole);
 const [current,setCurrent]=useState<Investigation|null>(initialInvestigation??null);const [loading,setLoading]=useState(initialInvestigation===undefined);const [error,setError]=useState('');
 const [batches,setBatches]=useState<CdiscPublishedBatch[]>([]);const [batchError,setBatchError]=useState('');const [launching,setLaunching]=useState(false);
 const [view,setView]=useState<'dynamic'|'investigation'|'understanding'|'import'|'catalog'>(initialInvestigation!==undefined?'investigation':'dynamic');
 useEffect(()=>{if(initialInvestigation!==undefined)return;setLoading(true);Promise.all([listInvestigations(role),listPublishedCdiscBatches(role)]).then(([items,versions])=>{setCurrent(items[0]??null);setBatches(versions)}).catch(e=>{setError(e.message);listPublishedCdiscBatches(role).then(setBatches).catch(()=>setBatchError('无法加载已发布数据版本'))}).finally(()=>setLoading(false))},[initialInvestigation,role]);
 const handleCreated=(item:Investigation)=>{setCurrent(item);setLaunching(false)};
 return <div className="app-shell">
  <a className="skip-link" href="#main-workspace">跳到主要内容</a>
  <Header aria-label="InsightFlow Clinical"><HeaderName href="#" prefix=""><span className="brand-mark"><Activity size={19}/></span><span className="brand-name">InsightFlow</span><span className="brand-domain">Clinical</span></HeaderName><div className="system-live"><i/><span>分析服务在线</span></div><label className="role-switch"><span>演示身份</span><select aria-label="演示角色" value={role} onChange={e=>setRole(e.target.value as Role)}><option value="admin">管理员</option><option value="analyst">临床分析师</option><option value="viewer">审阅者</option></select></label><span className="role-name">{{admin:'管理员',analyst:'临床分析师',viewer:'审阅者'}[role]}</span></Header>
  <nav className="rail" aria-label="工作台导航"><div className="rail-title"><strong>临床调查台</strong><span>Research operations</span></div><div className="nav-cluster"><button className={view==='dynamic'?'nav-active':''} onClick={()=>setView('dynamic')}><Document size={18}/><span>动态调查</span></button><button className={view==='catalog'?'nav-active':''} onClick={()=>setView('catalog')}><DataBase size={18}/><span>数据目录</span></button><button className={view==='understanding'?'nav-active':''} onClick={()=>setView('understanding')}><DataBase size={18}/><span>数据理解</span></button><button className={view==='investigation'?'nav-active':''} onClick={()=>setView('investigation')}><Time size={18}/><span>历史调查</span></button><button className={view==='import'?'nav-active':''} onClick={()=>setView('import')}><Upload size={18}/><span>CDISC 导入</span></button>{role==='admin'&&<button><span>审批队列</span></button>}</div><div className="rail-foot"><i/>API 与数据库在线</div></nav>
  <Content id="main-workspace" className="workspace">{view==='dynamic'?<InvestigationComposer role={role} onCompleted={()=>{}}/>:view==='catalog'?<DataCatalogPanel role={role}/>:view==='understanding'?<DataUnderstandingWorkspace role={role}/>:view==='import'?<CdiscImportWorkspace role={role}/>:current?.state.domain==='clinical_trial'?<><PublishedBatchBar batches={batches} error={batchError}/><ClinicalSafetyPanel investigation={current} role={role} loading={loading} error={error||undefined}/></>:loading?<Loading/>:error?<ErrorState message={error}/>:!current?<><PublishedBatchBar batches={batches} error={batchError}/>{launching?<InvestigationLauncher role={role} batches={batches} onCreated={handleCreated} onCancel={()=>setLaunching(false)}/>:<Empty onStart={()=>setLaunching(true)} role={role}/>}</>:<><PublishedBatchBar batches={batches} error={batchError}/><InvestigationView item={current} role={role}/></>}</Content>
 </div>
}
function Loading(){return <section aria-label="正在加载" className="skeleton"><div/><div/><div/></section>}
function ErrorState({message}:{message:string}){return <section className="empty"><h1>调查加载失败</h1><p>{message}</p><Button onClick={()=>location.reload()}>重新加载</Button></section>}
function Empty({onStart,role}:{onStart:()=>void;role:Role}){return <section className="empty"><DataBase size={40}/><h1>还没有临床调查</h1><p>提交受治理的试验问题，InsightFlow Clinical 会建立可审计的证据链并进入人工审批。</p>{role==='viewer'?<p>查看者无权创建调查（Viewer cannot create investigations）。</p>:<Button onClick={onStart}>开始临床调查</Button>}</section>}
function PublishedBatchBar({batches,error}:{batches:CdiscPublishedBatch[];error:string}){if(error)return <div className="version-notice">数据版本（Data version）加载失败：{error}</div>;if(!batches.length)return null;return <section className="version-bar"><div><p className="kicker">数据版本（Data Version）</p><strong>已发布临床批次（Published CDISC batches）</strong></div><span>{batches.length} 个可用版本（available）</span></section>}
function InvestigationLauncher({role,batches,onCreated,onCancel}:{role:Role;batches:CdiscPublishedBatch[];onCreated:(item:Investigation)=>void;onCancel:()=>void}){
 const firstTrial=batches[0]?.trial_ids[0]??'TRIAL-CF-101';const [trialId,setTrialId]=useState(firstTrial);const [question,setQuestion]=useState('为什么这个试验的 Week-12 疗效存在差异？');const [subgroup,setSubgroup]=useState('Asia');const [batchId,setBatchId]=useState(batches[0]?.batch_id??'');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const submit=async()=>{if(!trialId||question.length<5){setError('请输入试验编号和至少 5 个字符的问题');return}setBusy(true);setError('');try{onCreated(await createClinicalInvestigation({trial_id:trialId,question,subgroup:subgroup||undefined,batch_id:batchId||undefined},role))}catch(e){setError(e instanceof Error?e.message:'创建调查失败')}finally{setBusy(false)}};
 const chooseBatch=(value:string)=>{setBatchId(value);const selected=batches.find(item=>item.batch_id===value);if(selected?.trial_ids[0])setTrialId(selected.trial_ids[0])};
 return <section className="empty launcher"><p className="kicker">新建调查（New Investigation）</p><h1>选择数据版本并提出临床问题</h1><p>调查会固定使用所选已发布批次；缺失的安全性、暴露或访视域会明确标记证据不足，不会回退到其他版本。</p><label>试验编号（Trial ID）<input value={trialId} onChange={e=>setTrialId(e.target.value)} /></label><label>业务问题（Question）<textarea value={question} onChange={e=>setQuestion(e.target.value)} rows={4}/></label><label>亚组（Subgroup，可选）<input value={subgroup} onChange={e=>setSubgroup(e.target.value)} /></label><label>数据版本（Published Batch）<select aria-label="数据版本（Data Version）" value={batchId} onChange={e=>chooseBatch(e.target.value)}><option value="">默认治理数据（Governed default）</option>{batches.map(item=><option key={item.batch_id} value={item.batch_id}>{item.batch_id} · {item.trial_ids.join(', ')} · {item.record_count} rows</option>)}</select></label>{batchId&&<div className="version-detail">已锁定（Bound）：{batches.find(item=>item.batch_id===batchId)?.batch_id}<br/>域覆盖（Domain coverage）：{Object.entries(batches.find(item=>item.batch_id===batchId)?.domain_coverage??{}).filter(([,ok])=>ok).map(([domain])=>domain).join('、')||'未提供'}</div>}{error&&<div role="alert" className="import-error">{error}</div>}<div className="launcher-actions"><Button kind="secondary" onClick={onCancel}>取消</Button><Button disabled={busy||role==='viewer'} onClick={submit}>{busy?'正在创建…':'开始调查（Start）'}</Button></div></section>
}
function InvestigationView({item,role}:{item:Investigation;role:Role}){const state=item.state;return <>
 <header className="page-head"><div><p className="kicker">调查工作台（Investigation Workspace）</p><h1>{state.question}</h1><p className="meta">{state.metric??'待识别指标'} · 负责人（Owner） {item.owner_user_id}</p></div><div className="head-status"><Tag type={item.publication_status==='published'?'green':'warm-gray'}>{labels[item.publication_status]??item.publication_status}</Tag><strong>{Math.round(state.confidence*100)}%</strong><span>置信度（Confidence）</span></div></header>
 <div className="layout"><section className="timeline"><h2>调查时间线（Investigation Timeline）</h2>{state.steps.map(step=><article key={step.sequence}><span>{step.sequence}</span><div><strong>{step.tool}</strong><p>{step.summary}</p></div></article>)}</section>
 <section className="report"><h2>业务结论（Executive Summary）</h2><p className="answer">{state.answer}</p><Tabs><TabList aria-label="调查详情"><Tab>证据（Evidence）</Tab>{role!=='viewer'&&<Tab>查询语句（SQL）</Tab>}<Tab>数据来源（Sources）</Tab></TabList><TabPanels><TabPanel><div className="evidence-list">{state.evidence.map(e=><article key={e.evidence_id}><div><Tag size="sm">{e.evidence_id}</Tag><strong>{e.claim}</strong></div><p>{e.source} · 样本量（Sample） {e.sample_size??'暂无'}</p></article>)}</div></TabPanel>{role!=='viewer'&&<TabPanel>{state.evidence.map(e=><pre key={e.evidence_id}>{e.sql}</pre>)}</TabPanel>}<TabPanel>{[...new Set(state.evidence.map(e=>e.source))].map(x=><p key={x}>{x}</p>)}</TabPanel></TabPanels></Tabs></section></div>
 </>}

