import {useState} from 'react';
import {Button,InlineLoading,Tag,TextArea} from '@carbon/react';
import type {CdiscBatch,CdiscPreview,CdiscPublishAssessment,Role,SmartImportInspection} from '../types';
import {assessCdiscPublish,commitCdiscImport,inspectClinicalFiles,previewCdiscImport,previewSmartClinicalFiles,publishCdiscBatch} from '../api';

const standardMapping=JSON.stringify({dm:{},adsl:{},adeff:{}},null,2);
type Files={dm:File;adsl:File;adeff:File};
type SmartPreview=(files:File[],mapping:string)=>Promise<CdiscPreview>;

export function CdiscImportWorkspace({role,previewImport,commitImport,assessPublish,publishBatch,inspectFiles,previewSmart}:{role:Role;previewImport?:(files:Files,mapping:string)=>Promise<CdiscPreview>;commitImport?:(token:string)=>Promise<CdiscBatch>;assessPublish?:(batchId:string)=>Promise<CdiscPublishAssessment>;publishBatch?:(batchId:string)=>Promise<CdiscBatch>;inspectFiles?:(files:File[])=>Promise<SmartImportInspection>;previewSmart?:SmartPreview}){
 const [selected,setSelected]=useState<Partial<Files>>({});const [mapping,setMapping]=useState(standardMapping);const [preview,setPreview]=useState<CdiscPreview|null>(null);const [batch,setBatch]=useState<CdiscBatch|null>(null);const [assessment,setAssessment]=useState<CdiscPublishAssessment|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const [smartFiles,setSmartFiles]=useState<File[]>([]);const [inspection,setInspection]=useState<SmartImportInspection|null>(null);
 if(role==='viewer')return <section className="import-workspace"><p className="kicker">数据接入（Data Ingestion）</p><h1>CDISC 数据导入</h1><div className="notice">查看者无权上传临床数据</div></section>;
 const choose=(key:keyof Files)=>(event:React.ChangeEvent<HTMLInputElement>)=>setSelected(x=>({...x,[key]:event.target.files?.[0]}));
 const inspect=async()=>{if(!smartFiles.length){setError('请至少选择一个临床数据文件');return}setBusy(true);setError('');try{setInspection(await (inspectFiles??(items=>inspectClinicalFiles(items,role)))(smartFiles));setPreview(null)}catch(e){setError(e instanceof Error?e.message:'智能文件识别失败')}finally{setBusy(false)}};
 const smartMapping=()=>JSON.stringify({files:(inspection?.files??[]).map(file=>({filename:file.filename,domain:file.domain,fields:Object.fromEntries(file.fields.filter(field=>field.source_field).map(field=>[field.target_field,field.source_field]))}))});
 const runSmartPreview=async()=>{if(!inspection?.ready_for_preview){setError('请先确认所有数据域和关键字段映射');return}setBusy(true);setError('');setBatch(null);setAssessment(null);try{setPreview(await (previewSmart??((files,m)=>previewSmartClinicalFiles(files,m,role)))(smartFiles,smartMapping()))}catch(e){setError(e instanceof Error?e.message:'智能映射质量预检失败')}finally{setBusy(false)}};
 const runPreview=async()=>{if(!selected.dm||!selected.adsl||!selected.adeff){setError('请选择全部三个 CDISC CSV 文件');return}setBusy(true);setError('');setBatch(null);setAssessment(null);try{setPreview(await (previewImport??((f,m)=>previewCdiscImport(f,m,role)))(selected as Files,mapping))}catch(e){setError(e instanceof Error?e.message:'质量预检失败')}finally{setBusy(false)}};
 const commit=async()=>{if(!preview)return;setBusy(true);setError('');try{const committed=await (commitImport??commitCdiscImport)(preview.token);setBatch(committed);setAssessment(await (assessPublish??assessCdiscPublish)(committed.batch_id))}catch(e){setError(e instanceof Error?e.message:'确认导入失败')}finally{setBusy(false)}};
 const publish=async()=>{if(!batch)return;setBusy(true);setError('');try{setBatch(await (publishBatch??publishCdiscBatch)(batch.batch_id))}catch(e){setError(e instanceof Error?e.message:'发布到分析层失败')}finally{setBusy(false)}};
 return <section className="import-workspace"><p className="kicker">智能数据接入</p><h1>让不同格式的数据说同一种临床语言</h1><p className="import-lead">上传文件后，系统自动识别数据域和字段含义，并解释每个映射。模型只提出建议；规则校验和人工确认决定是否入库。</p>
  <section className="smart-drop"><div><span className="step-mark">第一步</span><h2>放入临床数据文件</h2><p>默认支持 Excel（XLSX）、CSV、TSV、JSON 与 JSONL；Parquet、XPT 通过可选插件接入，缺少插件时会给出安装提示。</p></div><label className="drop-target">选择临床数据文件<input aria-label="选择临床数据文件" type="file" multiple accept=".csv,.tsv,.json,.jsonl,.xlsx,.parquet,.xpt" onChange={e=>setSmartFiles(Array.from(e.target.files??[]))}/><strong>{smartFiles.length?`已选择 ${smartFiles.length} 个文件`:'拖入或选择多个文件'}</strong><span>单批最多 20 个文件，总计不超过 25 MB</span></label><Button disabled={busy||!smartFiles.length} onClick={inspect}>自动识别并匹配</Button></section>
  {inspection&&<section className="mapping-review"><header><div><span className="step-mark">第二步</span><h2>检查自动映射</h2></div><Tag type={inspection.ready_for_preview?'green':'warm-gray'}>{inspection.ready_for_preview?'可以预检':'需要人工确认'}</Tag></header>{inspection.files.map(file=><article key={file.filename}><div className="file-summary"><strong>{file.filename}</strong><span>{file.format.toUpperCase()} · {file.row_count} 行</span><b aria-label={`识别置信度 ${Math.round(file.confidence*100)}%`}>{file.domain.toUpperCase()} · {Math.round(file.confidence*100)}%</b></div><div className="mapping-list">{file.fields.map(field=><div key={field.target_field}><code>{field.source_field??'未匹配'}</code><span>映射到</span><strong>{field.target_field}</strong><em>{Math.round(field.confidence*100)}%</em><p>{field.reason}</p></div>)}</div></article>)}<Button disabled={busy||!inspection.ready_for_preview} onClick={runSmartPreview}>运行智能质量预检</Button></section>}
  {busy&&<InlineLoading description="正在识别结构并校验映射"/>}{error&&<div role="alert" className="import-error">{error}</div>}
  <details className="legacy-import"><summary>使用标准 CDISC 三文件快速导入</summary><ol className="import-steps"><li className="active">1 选择文件</li><li className={Object.keys(selected).length===3?'active':''}>2 字段映射</li><li className={preview?'active':''}>3 质量预检</li><li className={batch?'active':''}>4 确认导入</li><li className={batch?.status==='published'?'active':''}>5 分析发布</li></ol><div className="import-grid"><section className="import-card"><h2>标准源文件</h2>{([['dm','DM 人口学数据'],['adsl','ADSL 受试者级分析数据'],['adeff','ADEFF 疗效分析数据']] as const).map(([key,label])=><label className="file-field" key={key}>{label}<input aria-label={label} type="file" accept=".csv,text/csv" onChange={choose(key)}/><span>{selected[key]?.name??'尚未选择'}</span></label>)}</section><section className="import-card"><h2>字段映射</h2><TextArea id="mapping" labelText="映射配置 JSON" rows={8} value={mapping} onChange={e=>setMapping(e.target.value)}/><Button disabled={busy} onClick={runPreview}>运行质量预检</Button></section></div></details>
  {preview&&<section className="quality-panel"><div className="quality-title"><div><Tag type="green">通过</Tag><h2>质量预检通过</h2></div><strong>{preview.quality.completeness_percent}%</strong></div><div className="quality-metrics"><span>DM 行数<strong>{preview.quality.rows.dm}</strong></span><span>ADSL 行数<strong>{preview.quality.rows.adsl}</strong></span><span>ADEFF 行数<strong>{preview.quality.rows.adeff}</strong></span><span>试验<strong>{preview.quality.trial_ids.join(', ')}</strong></span><span>中心数<strong>{preview.quality.site_ids.length}</strong></span></div><h3>脱敏预览</h3><div className="preview-table"><div>假名标识</div><div>试验</div><div>中心</div><div>治疗组</div>{preview.preview.map(row=><div className="preview-row" key={row.participant_key}><code>{row.participant_key}</code><span>{row.trial_id}</span><span>{row.site_id}</span><span>{row.arm}</span></div>)}</div>{role==='admin'&&<Button disabled={busy||!!batch} onClick={commit}>确认导入</Button>}{batch&&<div className="import-success"><strong>导入批次已保存</strong><span>批次 {batch.batch_id} · {batch.record_count} 条规范记录</span></div>}{assessment&&batch?.status!=='published'&&<div className={assessment.eligible?'import-success':'import-error'}><strong>{assessment.eligible?'满足分析发布条件':'未满足分析发布条件'}</strong><span>总样本 {assessment.record_count} · 对照组 {assessment.arm_counts.control??0} · 治疗组 {assessment.arm_counts.treatment??0}</span>{assessment.failed_rules.length>0&&<span>未通过规则：{assessment.failed_rules.join('、')}</span>}{assessment.eligible&&<Button disabled={busy} onClick={publish}>发布到分析层</Button>}</div>}{batch?.status==='published'&&<div className="import-success"><strong>已发布到分析层</strong><span>该批次现已进入受治理的 dbt 分析模型。</span></div>}</section>}
 </section>
}

